### ISSUE TITLE
Может создать две константы Person

### ISSUE THREAD

**Issue by AndreyShovkun** [AndreyShovkun/my_test_project#22]
### Discussed in https://github.com/AndreyShovkun/my_test_project/discussions/20

<div type='discussions-op-text'>

<sup>Originally posted by **Legrendorg** August 23, 2023</sup>
**Может создать две константы Person, в этих константах будут лежать по 5 значений.**
Константы должны быть в качестве массива</div>

**Comment by Legrendorg** [comment]
Давайте я это заделаю
